### ISSUE TITLE
Excutable or script Autolisp package

### ISSUE THREAD

**Issue by Leftdefense** [ten0s/velisp#1]
Hi,

I don't know much about your project but i'm really interested in it. I'm creating really useful tools for my co-workers using AutoLISP from within Bricscad and i was wondering if i could export my code outside of Bricscad.

Could your solution, coded to call my lisp file, be compiled into an executable or a robust script that a user could run without the need to install anything? For example, the user would simply need to click the executable shortcut and the lisp coded DCL would appear to him.

Thanks.

**Comment by ten0s** [comment]
Hi,

> I don't know much about your project but i'm really interested in it. I'm creating really useful tools for my co-workers using AutoLISP from within Bricscad and i was wondering if i could export my code outside of Bricscad.

This is one of the purpose of this project. If your code doesn't use {Auto,Brics,..}CAD specific functionality like drawing, it might be runnable by VeLisp.

> Could your solution, coded to call my lisp file, be compiled into an executable or a robust script that a user could run without the need to install anything? For example, the user would simply need to click the executable shortcut and the lisp coded DCL would appear to him.

What is your target platform to run an executable bundle on (Windows, Linux, Mac)? 

VeLisp is a regular interpreter like Python or Node.js. If you have **YOUR.LSP** and **YOUR.DCL** files then it should be possible to run like:

```
$ velisp YOUR.LSP
```

Anyway, before thinking about the bundle, you should first make you code runnable by VeLisp. VeLisp is early release. Thus, for every example so far I had to make some changes (big or small) in VeLisp to make them work. :)

See the examples directory (https://github.com/ten0s/velisp/tree/master/examples) and implemented functions pages (https://github.com/ten0s/velisp#implemented-functions).

**Comment by ten0s** [comment]
Hi,

I've made a very interesting research regarding your original question. 

The below is how to make an executable for the **calc** example (https://github.com/ten0s/velisp/blob/master/examples/calc.lsp, https://github.com/ten0s/velisp/blob/master/examples/calc.dcl).

1. Download the package [calc.zip](https://github.com/ten0s/velisp/files/9847020/calc.zip)
2. Extract it to some directory
3. Download https://github.com/ten0s/velisp/releases/download/0.7.1/velisp-0.7.1-win-x64.zip to the directory
4. The directory should look like the below:
![image](https://user-images.githubusercontent.com/1344415/197404335-fcbd15de-cbaa-46f8-9f5f-29096d7e448c.png)
5. Run **build.cmd**
6. After a while **calc.exe** should be created
![image](https://user-images.githubusercontent.com/1344415/197404408-33b73eef-1536-4d7f-a5e0-2be04ed38e2d.png)
7. Run **calc.exe**
![image](https://user-images.githubusercontent.com/1344415/197404438-c1e40dab-4846-4bb7-b0a3-f1b9249c8cc7.png)

Take a look at **calc.sed** file which is a configuration file for https://en.wikipedia.org/wiki/IExpress. You may want to change
all **calc** entries to something specific to your apps.

Hope this helps.

**Comment by Leftdefense** [comment]
Hi Ten0s!
Of course it helps. What a wonderful solution! That perfectly materializes my wish. Thanks.

I have a project in mind using your solution that i would use to query a database and open a directory, and the code could be shared with my custom AutoCad tool doing the same thing.
I would list my needs in terms of implementation whenever i get the time do to so.

PS: i noted that i was not able to create the calc.exe using your latest build (velisp-0.7.3-win-x64.zip) even though i adjusted the .sed file to look for the 0.7.3 version. I got a error message from IExpress wizard saying : «_Unable to end update of resources._» and no .exe was created. It worked as expected using the 0.7.1.
