### ISSUE TITLE
Evaluation of three nested "cons"

### ISSUE THREAD

**Issue by EvgenyVenalainen** [ten0s/velisp#5]
Trying to evaluate "(cons 1 (cons 2 (cons 3 4)))" VeLisp allocates a lot of memory and then being closed by itself.
![VeLisp 3xCons](https://user-images.githubusercontent.com/96023196/213589583-b6df2588-ec7d-46f8-947b-44fdd976cb23.png)

**Comment by ten0s** [comment]
Thank you!

**Comment by ten0s** [comment]
Fixed in [0.7.7](https://github.com/ten0s/velisp/releases/tag/0.7.7)
